"""
Experience bullet library — generated by /setup.
Run /setup first to populate this file with your work history.

Usage in a job script:
    from tools.content import role_company1, role_company2, ...

    experience = [
        role_company1(["key1", "key2", "key3"]),
        role_company2(),
    ]

Keys let you select which bullets to include per role. Order is preserved.
Read this file to see all available role functions and their keys before filling template.py.
"""


def _pick(library, keys):
    return [library[k] for k in (keys or library)]


# Role functions are generated here by /setup.
# After running /setup, this file will contain your personalized bullet library
# with role_<companyslug> functions and named bullet keys for each role.
